name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.x
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # Install dependencies in subdirectory
      - name: Install dependencies
        run: npm install
        working-directory: ./course-subscription-app

      # Run tests (optional)
      - name: Run tests
        run: npm test
        working-directory: ./course-subscription-app

      # Build the project
      - name: Build project
        run: npm run build
        working-directory: ./course-subscription-app

      # Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './course-subscription-app/dist' # Adjust based on your build output directory
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
